services:
  mondodb:
    image: mongodb:v1
    container_name: mongodb
  catalouge:
    image: catalouge:v1
    container_name: catalouge
    depends_on:
      - mondodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: true